// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yykivairhgojinayhkde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5a2l2YWlyaGdvamluYXloa2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDYyMDcsImV4cCI6MjA1ODk4MjIwN30.xn8T6kv8JPwOu1ChqU4CU6rCaGGc0jy2scbEWeXU9WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);